name: Security scan

on:
  push:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Run security scan
      uses: find-sec-bugs/find-sec-bugs-action@v2.0.2
      with:
        classpath: ./target/classes
        exclude: "BOD,EXS"
        jvmArgs: "-Dfindbugs.threshold=High"
